# Case_2
- By using list()

In [ ]:
# list(Iterable)- It returns a list (Typecasting)

In [ ]:
# list(enumerate_object)
# list(zip_object)
# list(filter_object)
# list(map_object)

### filter()

In [ ]:
# - filter() filters the values from an iterable and returns a filter object.
# - To extract the values from tehe filter object we pass it to the list()

In [ ]:
t=(1,2,3,4,5,6,7,8,9,10)
f=filter(lambda x:x%2==0,t)
print(f,type(f))
lst=list(f)
print(lst,type(lst))

<filter object at 0x0000028071131BD0> <class 'filter'>
[2, 4, 6, 8, 10] <class 'list'>


### map()

In [ ]:
# - map() is used to apply element by element operation on an iterable.
# - map() returns a map object.
# - To extract the values from a map object we pass it to the list().

In [ ]:
t=(1,2,3,4,5,6,7,8,9,10)
m=map(lambda x:x**2,t)
print(m,type(m))
lst=list(m)
print(lst,type(lst))

<map object at 0x0000028071130B80> <class 'map'>
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100] <class 'list'>


# Case_3
- By taking the input from the user

In [ ]:
lst=list(input('Enter some values- '))
print(lst,type(lst))

Enter some values-  Hello


['H', 'e', 'l', 'l', 'o'] <class 'list'>


In [ ]:
print(list('Hello'))

['H', 'e', 'l', 'l', 'o']


In [ ]:
lst=list(input('Enter some values- '))
print(lst,type(lst))

Enter some values-  12345


['1', '2', '3', '4', '5'] <class 'list'>


In [ ]:
print(list('12345'))

['1', '2', '3', '4', '5']


In [ ]:
lst=list(input('Enter some values- '))
print(lst,type(lst))

Enter some values-  Python class


['P', 'y', 't', 'h', 'o', 'n', ' ', 'c', 'l', 'a', 's', 's'] <class 'list'>


In [ ]:
print(list('Python class'))

['P', 'y', 't', 'h', 'o', 'n', ' ', 'c', 'l', 'a', 's', 's']


In [ ]:
# Output- ['Python','Class']

# eval()

In [ ]:
# - It evaluates the type of the value passed to it.
# - It always takes a string value.

In [ ]:
a=eval('5')
print(a,type(a))

5 <class 'int'>


In [ ]:
a=eval('5.7')
print(a,type(a))

5.7 <class 'float'>


In [ ]:
a=eval('[1,2,3,4,5]')
print(a,type(a))

[1, 2, 3, 4, 5] <class 'list'>


In [ ]:
["Python","Class"]

['Python', 'Class']

In [ ]:
a=eval('["Python","Class"]')
print(a,type(a))

['Python', 'Class'] <class 'list'>


In [ ]:
lst=eval(input('Enter a list'))
print(lst,type(lst))

Enter a list ["Python",'Class']


['Python', 'Class'] <class 'list'>


In [ ]:
# Output- [10,20,30,40,50]

In [ ]:
lst=list(input('Enter values- '))
print(lst,type(lst))

Enter values-  10,20,30,40,50


['1', '0', ',', '2', '0', ',', '3', '0', ',', '4', '0', ',', '5', '0'] <class 'list'>


In [ ]:
print(list('10,20,30,40,50'))

['1', '0', ',', '2', '0', ',', '3', '0', ',', '4', '0', ',', '5', '0']


In [ ]:
lst=eval(input('Enter a list'))
print(lst,type(lst))

Enter a list [10,20,30,40,50]


[10, 20, 30, 40, 50] <class 'list'>


In [ ]:
lst=[]

for i in range(5):
    val=eval(input('Enter a value- '))
    lst.append(val)

print(lst,type(lst))

Enter a value-  10
Enter a value-  2.5
Enter a value-  "Python"
Enter a value-  True
Enter a value-  5+5j


[10, 2.5, 'Python', True, (5+5j)] <class 'list'>


# Case_4
- By using list comprehension

In [ ]:
# - It is a one liner code to create a list using loop.
# - It is an easier method to create a list using loop.

### Syntax-

In [ ]:
# [value for loop]
# [value for positioner in iterable]

In [ ]:
lst=['a' for i in range(5)]
print(lst,type(lst))

['a', 'a', 'a', 'a', 'a'] <class 'list'>


In [ ]:
lst=[]

for i in range(5):
    lst.append('a')

print(lst,type(lst))

['a', 'a', 'a', 'a', 'a'] <class 'list'>


In [ ]:
# Create a list of numbers from 1 to 10 using list comprehension

In [ ]:
lst=[]
for i in range(1,11):
    lst.append(i)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
lst=[i for i in range(1,11)]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# [value for loop if condition]

In [ ]:
t=(1,5,4,9,8,3,7,5,4,12,15,78,6,41,66)
# Create a list of even numbers from the above tuple usimng list comprehension

In [ ]:
lst=[]
for i in t:
    if i%2==0:
        lst.append(i)
print(lst)

[4, 8, 4, 12, 78, 6, 66]


In [ ]:
lst=[i for i in t if i%2==0]
print(lst)

[4, 8, 4, 12, 78, 6, 66]


In [ ]:
codes=(111,118,None,121,None, 115, None, 116)
# Create a list of the valid codes from the above tuple using list comprehension

In [ ]:
lst=[]
for i in codes:
    if not i==None:
        lst.append(i)
print(lst)

[111, 118, 121, 115, 116]


In [ ]:
lst=[i for i in codes if i!=None]
print(lst)

[111, 118, 121, 115, 116]


In [ ]:
t=(1,5,4,9,8,3,7,5,4,12)
# Square the even numbers and cube the odd numbers from the above tuple and create a list

In [ ]:
lst=[]
for i in t:
    if i%2==0:
        lst.append(i**2)
    else:
        lst.append(i**3)

print(lst)

[1, 125, 16, 729, 64, 27, 343, 125, 16, 144]


In [ ]:
# [Ternary operator for loop]

In [ ]:
print(t)

(1, 5, 4, 9, 8, 3, 7, 5, 4, 12)


In [ ]:
lst=[i**2 if i%2==0 else i**3 for i in t]
print(lst)

[1, 125, 16, 729, 64, 27, 343, 125, 16, 144]


In [ ]:
i=4
i**2 if i%2==0 else i**3

16

In [ ]:
lst=['even' if i%2==0 else 'odd' for i in t]
print(lst)

['odd', 'odd', 'even', 'odd', 'even', 'odd', 'odd', 'odd', 'even', 'even']


# Creating a 2-D list

In [ ]:
# - When we have a list with in another list then we call it as 2-D list.
# - When we repeat a 1-D list then we get a 2-D list.

In [ ]:
# [[]]

In [ ]:
lst=[[1,2,3],[1,2,3],[1,2,3]]
print(lst)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3],[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# The number of inner lists are the number of rows
# The number of elements in each list are the number of columns

In [ ]:
lst=[[1,2,3,4],[1,2,3,4],[1,2,3,4]]
print(lst)

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]


In [ ]:
# 3- rows
# 4- columns

In [ ]:
x=np.array(lst)
x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
x.shape

(3, 4)

### Creating a 2-D list using loop

In [ ]:
# Create a 3*4 list of numbers
# 3- rows
# 4- columns

In [ ]:
inn=[]
out=[]

for i in range(4):
    inn.append(i)
print(inn)
out.append(inn)
print(out)

[0, 1, 2, 3]
[[0, 1, 2, 3]]


In [ ]:
# Outer loop: > The number of rows
#     Inner loop: -> The number of values in each list (columns)

In [ ]:
inn=[]
out=[]
for i in range(3): # The number of rows
    for j in range(4): # The number of columns
        inn.append((j))
    out.append(inn)
    inn=[]
print(out)

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]


### Creating a 2-D list using list comprehension

In [ ]:
# Create a 3*4 list of numbers
# 3- rows
# 4- columns

In [ ]:
x=[i for i in range(4)]
x

[0, 1, 2, 3]

In [ ]:
[x for i in range(3)]

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]

In [ ]:
lst=[[i for i in range(4)] for j in range(3)]
print(lst)

[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]


# Creating a 3-D list

### Creating a 3-D list using loop

In [ ]:
# - When we repeat a 2-D list we get a 3-D list

In [ ]:
for loop: # Layers
    for loop: # Rows
        for loop: # Columns

In [ ]:
# Create a 2*3*4 list
# 2- layers
# 3- rows
# 4- columns

In [ ]:
inn=[]
mid=[]
final=[]

for i in range(2):
    for j in range(3):
        for k in range(4):
            inn.append(k)
        mid.append(inn)
        inn=[]
    final.append(mid)
    mid=[]

print(final)

[[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]]


In [ ]:
arr=np.array(final)

In [ ]:
arr

array([[[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [ ]:
arr.shape

(2, 3, 4)

### Creating a 3-D list using list comprehension

In [ ]:
# [[[cols]rows]layers]

In [ ]:
lst=[[[i for i in range(4)] for j in range(3)] for k in range(2)]
print(lst,type(lst))

[[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]] <class 'list'>


In [ ]:
np.array(lst)

array([[[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

# Maximum of a list

In [ ]:
lst=[2,6,8,4,15,7,6,2]
# Find the maximum of the list using loop

In [ ]:
print(max(lst))

15


In [ ]:
# Approach-
max=2
max>6
max=6
max>8
max=8
max
max>4
max>15
max=15
max>7
max>6
max>2

True

In [ ]:
lst=[2,6,8,4,15,7,6,2]
# Find the maximum of the list using loop

max=lst[0]
# print(max)

for i in lst:
    if max<i:
        max=i
print(max)

15


In [ ]:
lst=[2,6,8,4,15,7,6,2]
# Find the maximum of the list using loop

max=0
# print(max)

for i in lst:
    if max<i:
        max=i
print(max)

15


In [ ]:
lst=[-2,-5,-7,-3,-1,-8,-9,-11,-4]

max=lst[0]
# print(max)

for i in lst:
    if max<i:
        max=i
print(max)

-1


# Minimum of a list

In [ ]:
lst=[8,0,-5,4,-15,7,1,2]

min=lst[0]
for i in lst:
    if min>i:
        min=i
print(min)

-15


# Sorting a list using loop

In [ ]:
lst=[12,4,8,4,15,7,6,2]
for i in range(len(lst)):
    for j in range(i+1,len(lst)):
       if lst[i]>lst[j]:
           lst[i],lst[j]=lst[j],lst[i]
print(lst)

[2, 4, 4, 6, 7, 8, 12, 15]


In [ ]:
i=0
j=0

In [ ]:
a=5
b=3
if a>b:
    a,b=b,a
print(a)
print(b)

3
5


# List is mutable

### Mutability

In [ ]:
# - We can modify an element inside the container.
# - Item assignment is possible.
# - The address of the container remains the same before and after the modification.

In [ ]:
lst=[10,20,30,40,50]
print(lst,id(lst))

[10, 20, 30, 40, 50] 2750732637184


In [ ]:
lst[0]=True # Item assignment
print(lst,id(lst))

[True, 20, 30, 40, 50] 2750732637184


In [ ]:
lst[-1]=5+6j # Item assignment
print(lst,id(lst))

[True, 20, 30, 40, (5+6j)] 2750732637184


# List Methods

In [ ]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
# 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort'

# append()

In [ ]:
# - append() takes a value as an argument and appends (add) it at the end of the list.
# - It makes the changes in the existing list, It does not return any object.

In [ ]:
# lst.append(value)

In [ ]:
lst=[10,20,30,40,50]
print(lst)

lst.append(100)
print(lst)

lst.append((1,2,3,4))
print(lst)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 100]
[10, 20, 30, 40, 50, 100, (1, 2, 3, 4)]


In [ ]:
lst=[10,20,30,40,50]
x=lst.append(100)
print(x)

None


In [ ]:
print(lst)

[10, 20, 30, 40, 50, 100]


# extend()

In [ ]:
# - It takes an iterable as an input.
# - It appends the elements of the iterable to the list one by one.
# - It makes the changes in the existing list.
# - It does not return anything.

In [ ]:
# lst.extend(iterable)

In [ ]:
lst=[10,20,30,40]
print(lst,id(lst))

lst.extend('Python')
print(lst,id(lst))

[10, 20, 30, 40] 2750732889536
[10, 20, 30, 40, 'P', 'y', 't', 'h', 'o', 'n'] 2750732889536


In [ ]:
lst=[10,20,30,40]
print(lst)

lst.append('Python')
print(lst)

[10, 20, 30, 40]
[10, 20, 30, 40, 'Python']


In [ ]:
lst=[10,20,30,40]
print(lst)

lst.extend(([1,2,3],'Python',{1,2,3},{1:00,2:200}))
print(lst)

[10, 20, 30, 40]
[10, 20, 30, 40, [1, 2, 3], 'Python', {1, 2, 3}, {1: 0, 2: 200}]


In [ ]:
lst=[10,20,30,40,50,60,70,80]
x=lst.extend({4,5,6})
print(x)
print(lst)

None
[10, 20, 30, 40, 50, 60, 70, 80, 4, 5, 6]


In [ ]:
lst=[10,20]
lst.extend(True)

TypeError: 'bool' object is not iterable

# count()

In [ ]:
# - It returns the count of the specified values in a list.
# - If the value is not found then it returns 0.

In [ ]:
# lst.count(element)

In [ ]:
lst=[1,1,1,1,5,5,55,5,5,5,5,9,9,9,9,9,9,0]
print(lst.count(1))
print(lst.count(5))
print(lst.count(0))
print(lst.count(55))
print(lst.count(100))

4
6
1
1
0


# index()

In [ ]:
# - It returns the index of the first occurence from left to right of the specified element.
# - If the element is not found then it raises ValueError.

In [ ]:
# lst.index(element, start, stop)
# stop index is excluded

In [ ]:
lst=['Java','C','C++','Python','Java','C#','R','Python','Python','Scala']
print(lst.index('Java'))
print(lst.index('R'))
print(lst.index('Python'))
print(lst.index('Python',4))
print(lst.index('Java',1,5))

0
6
3
7
4


# insert()

In [ ]:
# - It is used to insert an element at a particluar index.
# - The exeisting element get shifted to the right.

In [ ]:
# lst.insert(index,element)

In [ ]:
lst=[10,20,30,40,50,60]

# Insert 50 at index 2

lst.insert(2,50)
print(lst)

[10, 20, 50, 30, 40, 50, 60]


In [ ]:
lst=[10,20,30,40,50,60]

lst.insert(-1,None)
print(lst)

[10, 20, 30, 40, 50, None, 60]


In [ ]:
lst=[10,20,30,40,50,60]
print(lst)
lst.insert(len(lst),True)
print(lst)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, True]


# pop()

In [ ]:
# - It takes the index as an argument and returns the elements at that index also removes it from the list.
# - By default it returns and removes the last element.
# - If the invalid index is there the it raises index error.

In [ ]:
# lst.pop(index)
# lst.pop()

In [ ]:
lst=[True, 'Python', 5+5j, None, 4500, 6.999999, False, 8400]
print(lst)

x=lst.pop(5)
print(x)
print(lst)

x=lst.pop()
print(x)
print(lst)

x=lst.pop()
print(x)
print(lst)

[True, 'Python', (5+5j), None, 4500, 6.999999, False, 8400]
6.999999
[True, 'Python', (5+5j), None, 4500, False, 8400]
8400
[True, 'Python', (5+5j), None, 4500, False]
False
[True, 'Python', (5+5j), None, 4500]


# remove()

In [ ]:
# - It takes an element as an argument.
# - It removes the first occurence of the specified element.
# - In case of invalid element it raies value error.

In [ ]:
# lst.remove(element)

In [ ]:
lst=[True, 'Python', 5+5j, None, 4500,True, 6.999999, False, 8400, None]
print(lst)

x=lst.remove(True)
print(x)
print(lst)

lst.remove(False)
print(lst)

lst.remove(None)
print(lst)

[True, 'Python', (5+5j), None, 4500, True, 6.999999, False, 8400, None]
None
['Python', (5+5j), None, 4500, True, 6.999999, False, 8400, None]
['Python', (5+5j), None, 4500, True, 6.999999, 8400, None]
['Python', (5+5j), 4500, True, 6.999999, 8400, None]


In [ ]:
lst.remove('Zebra')

ValueError: list.remove(x): x not in list

# reverse()

In [ ]:
# - It reverses a list.
# - It does not return a new list, It makes the changes in the existiing list

In [ ]:
lst=[True, 'Python', 5+5j, None, 4500,True, 6.999999, False, 8400, None]
print(lst)

lst.reverse()
print(lst)

[True, 'Python', (5+5j), None, 4500, True, 6.999999, False, 8400, None]
[None, 8400, False, 6.999999, True, 4500, None, (5+5j), 'Python', True]


In [ ]:
lst=[True, 'Python', 5+5j, None, 4500,True, 6.999999, False, 8400, None]
print(lst)

print(lst[::-1])
print(lst)

[True, 'Python', (5+5j), None, 4500, True, 6.999999, False, 8400, None]
[None, 8400, False, 6.999999, True, 4500, None, (5+5j), 'Python', True]
[True, 'Python', (5+5j), None, 4500, True, 6.999999, False, 8400, None]


# sort()

In [ ]:
# - It sorts a list in ascending order by default.
# - It does not return anything. It makes the changes in the existing list.

In [ ]:
lst=[8,4,9,3,7,5,9,0,4,5]
lst.sort()
print(lst)

[0, 3, 4, 4, 5, 5, 7, 8, 9, 9]


In [ ]:
lst=[8,4,9,3,7,5,9,0,4,5]
lst.sort(reverse=True)
print(lst)

[9, 9, 8, 7, 5, 5, 4, 4, 3, 0]


In [ ]:
lst=[8,4,9,3,7,5,9,0,4,5]
x=sorted(lst)
print(x)
print(lst)

[0, 3, 4, 4, 5, 5, 7, 8, 9, 9]
[8, 4, 9, 3, 7, 5, 9, 0, 4, 5]


In [ ]:
lst=[8,4,9,3,7,5,9,0,4,5]
x=sorted(lst,reverse=True)
print(x)
print(lst)

[9, 9, 8, 7, 5, 5, 4, 4, 3, 0]
[8, 4, 9, 3, 7, 5, 9, 0, 4, 5]


# clear()

In [ ]:
# - It removes all the elements from a list and makes it empty.

In [ ]:
lst=[8,4,9,3,7,5,9,0,4,5]
print(lst)

lst.clear()
print(lst)

[8, 4, 9, 3, 7, 5, 9, 0, 4, 5]
[]


# copy()

In [ ]:
# - It copies the elemnts of a list and returns a new list.

In [ ]:
x=[10,20,30,40,50]
y=x
print('x->',x)
print('y->',y)
x[0]=True
print('x->',x,id(x))
print('y->',y,id(y))

x-> [10, 20, 30, 40, 50]
y-> [10, 20, 30, 40, 50]
x-> [True, 20, 30, 40, 50] 2750737891008
y-> [True, 20, 30, 40, 50] 2750737891008


In [ ]:
x=[10,20,30,40,50]
y=x.copy()

print(x)
print(y)

x[0]=True
print(x)
print(y)

print(id(x),id(y),sep='\n')

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[True, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
2750737709376
2750737699584


In [ ]:
# Tuple, Dictionary, Functions